# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9eac2530eb0c309e16869195beebf531799f1a30a9084e300f0017b58550839d894b8ebd4dbd31fe79c0737aa870ef47f5f541dfd47a98f842b5d502b4a34614

test:
  secret_key_base: 9c7350d89844d25cef0c86526ddab96ae0bafc203124bee05b510f86b942685139d1420f65927587d143e044bc538f3fa3d7b8722a8c4c4e015efd22d34855e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
